# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 22:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('fromdate', models.DateField(verbose_name=datetime.date)),
                ('todate', models.DateField(verbose_name=datetime.date)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='joining',
            field=models.ManyToManyField(related_name='joinedby', to='happiness.User'),
        ),
        migrations.AddField(
            model_name='trip',
            name='plannedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='happiness.User'),
        ),
    ]
